version: '3'

services:

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    restart: always
  
  tests:
    build: .
    command: pytest tests
    depends_on:
      - selenium
    